### ISSUE TITLE
update readme to change addon folder name

### ISSUE THREAD

**Issue by srbrunner** [smp4903/FiveSecondRule#1]
You might want to update the readme to include information about renaming the file from wow-classic-five-second-rule to FiveSecondRule

**Comment by smp4903** [comment]
> You might want to update the readme to include information about renaming the file from wow-classic-five-second-rule to FiveSecondRule

Now updated the readme. The entire repository has also been renamed to simplify the entire proces. Also added a correctly named .zip file to WarcraftTavern instead of linking to the archive here on GitHub.

Thanks a lot!
