### ISSUE TITLE
Second Counter continues after death

### ISSUE THREAD

**Issue by forcymusic** [smp4903/FiveSecondRule#11]
![WoWScrnShot_090919_122846](https://user-images.githubusercontent.com/26632033/64524233-66d0d900-d2fe-11e9-83fc-b7be24617dd6.jpg)

I was drowning and regenerating mana, then I realized the bar is still going..

**Comment by smp4903** [comment]
@Forcy24 Hah, yea.. didn't think of that ;-) thanks a lot, will fix that.

**Comment by smp4903** [comment]
fixed in 767fcedf2c1ea71785800f031c2b66ba1b167519
