### ISSUE TITLE
Frame not movable

### ISSUE THREAD

**Issue by ghost** [smp4903/FiveSecondRule#13]
Whenever I press "unlock" in the settings menu, the bar disappears. 
I wont let me move the tick bar. Any idea about this? 
Version 1.4

**Comment by jebstern** [comment]
It's because of this commit: https://github.com/smp4903/FiveSecondRule/commit/8653672f409534d76e6d9b3f27271bf1b2e5d336

You can delete that line in `FiveSecondRule.lua`, then it's movable again.

@smp4903 Is there any reason for the frame strata? It is currently causing unwanted behaviour.

**Comment by smp4903** [comment]
@jebstern @Paulbsh That was a bad solution to another problem. One user reported issues with overlapping frames, and setting the strata fixed _that_ issue, but obviously created other far worse ones. 
Reverting until I implement are more suitable fix. Thanks!

**Comment by smp4903** [comment]
fixed in 15d8be661e784a78f8a1aa4d61e8c1202e4eb13f
