### ISSUE TITLE
Feature Request: Add option to toggle spark (or remove it)

### ISSUE THREAD

**Issue by HolyMateria** [smp4903/FiveSecondRule#14]
In the latest update you added a white spark to mana ticks and the five second rule. I use the addon at 117 width and 1 height so that it fits perfectly underneath my mana bar without being too much of an eye sore. My problem is that the spark doesn't scale to the height and it is quite unsightly to look at. I love the addon and really want to continue using it, so if you could add an option to disable the spark that would be amazing <3

**Comment by arphox** [comment]
+1, I just wanted to make an issue for it as well. Good advice: never implement anything without a feature toggle that has a chance of disturbing the user.

@HolyMateria, if you want to disable it, just get back to [Release 1.4](https://github.com/smp4903/FiveSecondRule/releases/tag/Release-1-4)

**Comment by farzher** [comment]
yea, remove or add an option. the spark looks awful. its updating at like 12 fps while my game is at 165

**Comment by smp4903** [comment]
@farzher @arphox @HolyMateria 

Thank you guys for the feedback! 

Considering your comments I will:

- Add an option to toggle the spark on/off.
- Add an input field to adjust the update frequency of the timer (in case you want higher FPS on the Spark)

**Comment by smp4903** [comment]
@farzher @arphox @HolyMateria

Version 1.10 now has a toggle for the spark.

The input field will come in 1.11 or 1.12 :-)

**Comment by smp4903** [comment]
Higher FPS is now standard with version 1.16.
