### ISSUE TITLE
ZIP download filename not recognized

### ISSUE THREAD

**Issue by theteapot** [smp4903/FiveSecondRule#15]
Just noticed that if you download using ZIP, you will get a folder called `FiveSecondRule-master`, which if you simply drag into your addons folder will not be recognized. Perhaps it would be useful to add a note in the readme telling people to remove the branch name, `-master`, if they get the addon in this way.

**Comment by tjkns94** [comment]
Agree with @theteapot, I ran into this issue too. I think adding some quick installation instructions to the README.md will resolve this point of friction.

**Comment by smp4903** [comment]
Not really much I can do about that, since that is how GitHub packages the files :/ You can install it using the Twitch App for automatic updates if you like.
