### ISSUE TITLE
errors since last update

### ISSUE THREAD

**Issue by mackay2k4** [smp4903/FiveSecondRule#18]
I get 100 error every second since the last update. 

![2019-10-12 02_15_38-WORLD OF WARCRAFT](https://user-images.githubusercontent.com/29505063/66691534-66c64f00-ec97-11e9-99df-45e8e5c3cb5f.png)

rolling back to release 1-8 then everything works but with changes made on the 11th October i get the above error.

**Comment by smp4903** [comment]
@mackay2k4 Thank you for reporting this issue! It has been fixed in the latest upgrade.
