### ISSUE TITLE
Feature Request: Disable 5 second rule (only show ticks) + keep ticks ticking

### ISSUE THREAD

**Issue by Wushengg** [smp4903/FiveSecondRule#19]
Would it be possible to add an option to disable the 5 second rule and only show mana ticks?

It would also be a nice feature if the mana ticks would keep ticking even when full mana. I understand that over time the ticker might go out of sync, but in some circumstances seeing the tick would be useful information even when full mana.

**Comment by smp4903** [comment]
@Wushengg Thank you for your suggestion! Keeping the mana ticks ticking could be an option for sure. I will consider it :-)

Thanks!

**Comment by alexzaworski** [comment]
Just wanted to give support to the idea of tracking ticks only— hugely useful in some situations. Specifically, when playing mage I try to start cast evocation right before a server tick.

I see this is tagged good first issue, I wouldn't mind working on it but I'm extremely new to addon dev/lua so would need some coaching.

**Comment by alexzaworski** [comment]
@Wushengg if you need this still here's a weakaura that does an okay job (sometimes wonky with things that increase mana regen):

```
!TAv6UnUnq43f)Re0MaF7ffylqIJCIl8k7AkND32TYMwIsMnkKcKuohf1p7D4HKpYX6fOq2cIdN5Bo4WzMWgHbHO7drX6FWNYCS4UptJvRc9Bu3TECsIKO(sOpqaxOwXfJZvuotcsOasX)DHurI)eLzy5jl)H(N1d2Kfb8pHtzaN998d8M6qDkxH1OyKzpkFIhtcrxmlyCiAjo6UubVGf3NNXfGg9Beo4dTA1TEV2DR3U1h61RDVWKZ60k0VjSt3gFOBNwTR3UtRUT7vUtlTy(T16cSdLGMMseslAbvemF(uoO8iWJ4qCrwSKSMWuOIKe6JHO59VafmhfCXuG1yYsGCGrGB8gnzWSrHid7WAcodcIvamrqmaGM4nAuj(ZTktcUnPipgEVvZjfSiDW4e8pVzbb(RoDZVTzH9jJhHZ2SiQqi8yer6tBw8XnlMXOQj8hiItQLNHFIiQbIv)LIfxim838f7KliR3bWtWfc8CcB95zyPQCdUyFuPjaN7k5pTzrR6aaFCxl8uWdwryBfR85v1XEI(szeevHyhSiS4dShIv)1M5pmy(KXF2B68bt9(9zqgynqNa)7f9(1D99D8Tx3K1AGXvao)zTA)1BZxLlAzdSN)5TzQ8rUI)GHxLOao3)U8hTcZsjX)iIajaMlAgzGfhHiKhZPwHcO3tmcEnrP)(KtnN4hhm5cEQGiL6lngqQPaiIR92s(VVClsMK82c4sLLg4Tr(3Kx55hg9EpEpmS9E8EmXR3t(9YcELqWUj87T4h56K7AKthwyGhxrmzi6vU98l2slHig(EIRdq0ks0DvL(K5KSSHXU9kGIsHOsHSv3UflO4LzG4illBR)QmDuGkFRjbwIMUb(N1Wu5MgXzZJ22jq)RP5Dvf(gg(ykIGHZUfQYB6X0STUxe9EBlNatrxHABbFgNbVlpHllmta1boca49yk745oHYOYvhn)kBFUybpFiBGGdrXLAsI)F65zIisfn6UNUYzcA83P3(xTnHlwoLK6AS7AmASuDofynZH)auGkHDwYfXeXCURxFNkk2o(gZVIMK(mCg2OBfH3)iS(5DmXelVRPskKSycjwkK4uWQ8nbvxSSyPDpB0CfHMUYyPOmo2nzdjYmStrMIwMOfbxsKMDPSuqfOPJVEM3bmvijZzqUTWe00EYbWOCXYlZGRqUHxU6kJGx4MncMoc)O9q1Eo3)ycapwnjvRET1ZBiXk9b4oXIlD4fIUmJ(8ZybuklGZbJlxNHLL4g9AK3GGdTiQjnqyoYd29GUe8YKXlDoya5rq)aFd1xVsWrKV1hQYaXUlXIVnB4zBxDgslG7cRKQJjthE9nABGcdB(LC5dQof0h(kYHDvg5nBp7uL6R03crp4MnTrRq0ZCyqj3qPCTrQ4rRlVWdCuVvjK04ycdYy8Uvp(jolFfwhQrjcOigm9hwzxBZDhOPAdiO(t988b3aunIia0HQLuDXoWVsOP2ACuMwTKkxO)3VafxqHIL27IOBgpD4Fm2p4IrgCJP7mDToaQbghvsSQ0LrZu3xvLCkZidrnpVrhircTg0z7MA1g(Fp
```

**Comment by smp4903** [comment]
@alexzaworski Cool :-) That's also one of the primary challenges with the addon. However, some of them have been handled. Take a bit more work to be a completely robust solution.

**Comment by smp4903** [comment]
@Wushengg This is now a feature in version 1.19 - go check it out :)
