### ISSUE TITLE
error in reset call

### ISSUE THREAD

**Issue by snapxo** [smp4903/FiveSecondRule#2]
```
  if msg == "reset" then
        print("Five Second Rule - RESET SIZE AND POSITION.");
        lock()     
 end
```
you should call `reset()` there

**Comment by smp4903** [comment]
Fixed in the current version, thank you for reporting and creating a PR :-)

**Comment by snapxo** [comment]
Np :) I am thinking about collaborating to a slightly different version with an alternative representation of the 5sec. May I ? And should I then branch your project so that you can put it in if you find this nice ?

**Comment by smp4903** [comment]
> Np :) I am thinking about collaborating to a slightly different version with an alternative representation of the 5sec. May I ? And should I then branch your project so that you can put it in if you find this nice ?

I'd love to collaborate! Been considering alternatives myself; some low-hanging fruits include using the Cooldown frames, since it's technically a cooldown. Any contributions will of course be clearly stated in any documentation and so on. During this purely for fun and out of interest :)

**Comment by snapxo** [comment]
Yup okay then I ll try to find some time doing this :) Although I will not be able to test that prior to release now ^^

**Comment by smp4903** [comment]
Yea time is a bit tight :-) If you want to, you can describe your thoughts here or create a new issue to keep track of everything. The API for Classic is similar to Retail (with many restrictions, tho), so we might be able to test some basics in Retail.
