### ISSUE TITLE
Color and alpha settings don't save and/or behave strangely

### ISSUE THREAD

**Issue by mcfry** [smp4903/FiveSecondRule#21]
Just documenting this real quick while I'm here

**Comment by smp4903** [comment]
@mcfry Not entirely sure what's up here, but I'll try to take a look at it. Could you be more specific? 
Thanks!

**Comment by jbc123** [comment]
I have noticed that the alpha slider seems to be reversed.
When changing the background, the foreground will return to default.. and vice versa.
The size and position values do not change the appearance.

I'm guessing something just isn't saving values properly. I can change either the fore or background of the mana tick or the status bar, but not both.

**Comment by smp4903** [comment]
@mcfry Issue is resolved in version 1.15.

Alpha is still reversed though. But really depends if you're thinking of opacity or transparency ;-)
