### ISSUE TITLE
Negative Tick Counter

### ISSUE THREAD

**Issue by UmptyMaDoo** [smp4903/FiveSecondRule#22]
I figured a video would be the easiest way to show replication.

Problem:
if you use anything that restores mana (e.g. water, mana gems, evocation, etc) somewhere in the middle of mana ticks, FSR will keep counting down into the negatives.
The only workaround i've found is to either reach full mana or stop and drink properly.

This is an issue if you attempt drink running and time the drink too early. 
(drinking just before a tick will restore mana as if drinking)
I'm not exactly sure what the threshold is to cause this bug, but it's somewhere between the middle to end.

https://www.youtube.com/watch?v=DAwJOgxtkkA

![image](https://user-images.githubusercontent.com/41746811/69997630-8d2f9a80-1522-11ea-8467-646727bd4c04.png)

**Comment by smp4903** [comment]
Hey @UmptyMaDoo 

I have now successfully recreated your issue and will look into it. That's a neat trick ;-)
