### ISSUE TITLE
"Always show mana ticks" on or off make no difference

### ISSUE THREAD

**Issue by Cantstandya** [smp4903/FiveSecondRule#23]
Hi, great addon but mine dont work as expected. No matter if i check or uncheck "Always show mana ticks" it keeps showing the ticks until my mana bar is full. 

Not many settings to try in the Interface options, is there any other way to fix this?

Restarting game, or /reload dont help.

**Comment by Cantstandya** [comment]
Im dumb didnt read correctly...but I found a new possible bug.

I have unchecked "Show mana ticks" and "Always show mana ticks" since I just wanna see the 5s countdown. But when its done it shows a blank white bar that is just stuck.
![1](https://user-images.githubusercontent.com/62057628/76409206-5f15ee00-638e-11ea-9291-ff9357cd3f15.png)

**Comment by smp4903** [comment]
@Cantstandya Hey, is this due to the background color of the statusbar being grey?
