### ISSUE TITLE
Dont show in new Interface panel

### ISSUE THREAD

**Issue by adrilopego** [smp4903/FiveSecondRule#26]
I download to use in Hardcore servers, but with the new retail interface in classic wow the FSR is not list as addon, then you cant move the bar or set it.

![image](https://github.com/smp4903/FiveSecondRule/assets/143030028/1b9b461e-6f4f-4697-875e-4f4bfb36857c)

when i enabled any addon, the addon list show up but FSR still dont list it.

![image](https://github.com/smp4903/FiveSecondRule/assets/143030028/4d26522a-33fd-4a4b-b3e0-080c62dd5911)

Even typing /fsr just options tab pop up

**Comment by gccmbr** [comment]
Same issue (options screen not appearing)

However, I found these work:
/fsr enable / disable
/fsr lock / unlock

Can manually edit the lua for further customization until fix is available

**Comment by smp4903** [comment]
Fixed.
