### ISSUE TITLE
Add on keeps turning off

### ISSUE THREAD

**Issue by 0rz42** [smp4903/FiveSecondRule#27]
I am playing SoD.

My FSR addon keeps getting disabled.  Every time I login, I have to go to my addon list and re-enable it.  All of my other addons remain enabled.  Not sure if this is an issue with the addon or something else with my WoW., but I figured that I would post here.

**Comment by mallison521** [comment]
Having the same issue

**Comment by 0rz42** [comment]
Thanks for posting.  I am glad that I am not the only one.  Hopefully the developer is still supporting this otherwise great addon.

**Comment by smp4903** [comment]
Thanks for letting me know, I will look into it.
Sorry for the inconvenience!

**Comment by dired** [comment]
i made a pull request, which would have to be tested

**Comment by smp4903** [comment]
Fixed in version 1.38 with the help of dired :)
