### ISSUE TITLE
Lua Error on Classic-Era

### ISSUE THREAD

**Issue by loading-ui** [smp4903/FiveSecondRule#29]
**I'm getting this lua error on the classic era client. I'm not sure if it's because of the recent client update or addon update. I've tried deleted the addon and reinstalling, but the same error still pops.**

Message: ...ace/AddOns/FiveSecondRule/Dependencies/UIFactory.lua:22: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
Time: Sat Jul 13 11:40:05 2024
Count: 1
Stack: ...ace/AddOns/FiveSecondRule/Dependencies/UIFactory.lua:22: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
[string "=[C]"]: in function `SetJustifyV'
[string "@Interface/AddOns/FiveSecondRule/Dependencies/UIFactory.lua"]:22: in function `MakeText'
[string "@Interface/AddOns/FiveSecondRule/Dependencies/UIFactory.lua"]:30: in function `MakeEditBox'
[string "@Interface/AddOns/FiveSecondRule/Modules/OptionsPanel.lua"]:196: in function `CreateGUI'
[string "@Interface/AddOns/FiveSecondRule/Modules/OptionsPanel.lua"]:20: in function <...rface/AddOns/FiveSecondRule/Modules/OptionsPanel.lua:17>

Locals: (*temporary) = FontString {
 0 = <userdata>
}
(*temporary) = "CENTER"

**When trying to access the options from /fsr, this lua error pops up:**

Message: ...face/AddOns/FiveSecondRule/Modules/SlashCommands.lua:35: attempt to call method 'PrintHelp' (a nil value)
Time: Sat Jul 13 11:41:50 2024
Count: 1
Stack: ...face/AddOns/FiveSecondRule/Modules/SlashCommands.lua:35: attempt to call method 'PrintHelp' (a nil value)
[string "@Interface/AddOns/FiveSecondRule/Modules/SlashCommands.lua"]:35: in function `?'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Classic/ChatFrame.lua"]:5016: in function `ChatEdit_ParseText'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Classic/ChatFrame.lua"]:4674: in function `ChatEdit_SendText'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Classic/ChatFrame.lua"]:4710: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:120_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:120_OnEnterPressed"]:1>

Locals: msg = ""
editbox = ChatFrame1EditBox {
 0 = <userdata>
 headerSuffix = ChatFrame1EditBoxHeaderSuffix {
 }
 tabCompleteTableIndex = 1
 chatLanguage = "Common"
 text = "/"
 setText = 0
 customAutoCompleteFunction = <function> defined @Interface/AddOns/Blizzard_ChatFrameBase/Classic/ChatFrame.lua:4199
 autoCompleteParams = <table> {
 }
 chatFrame = ChatFrame1 {
 }
 header = ChatFrame1EditBoxHeader {
 }
 addSpaceToAutoComplete = true
 addHighlightedText = true
 prompt = ChatFrame1EditBoxPrompt {
 }
 languageID = 7
 language = "Common"
}
cmd = ""
(*temporary) = nil
(*temporary) = Frame {
 0 = <userdata>
 mp5StartTime = 0
 previousPower = 303
 Refresh = <function> defined @Interface/AddOns/FiveSecondRule/FiveSecondRule.lua:180
 Unlock = <function> defined @Interface/AddOns/FiveSecondRule/FiveSecondRule.lua:185
 GetPowerType = <function> defined @Interface/AddOns/FiveSecondRule/FiveSecondRule.lua:157
 GetPower = <function> defined @Interface/AddOns/FiveSecondRule/FiveSecondRule.lua:149
 OptionsPanelFrame = FiveSecondRuleOptionsPanelFrame {
 }
 IsWOTLK = <function> defined @Interface/AddOns/FiveSecondRule/FiveSecondRule.lua:60
 Lock = <function> defined @Interface/AddOns/FiveSecondRule/FiveSecondRule.lua:192
 GetPowerMax = <function> defined @Interface/AddOns/FiveSecondRule/FiveSecondRule.lua:153
 UIFactory = <table> {
 }
 Reset = <function> defined @Interface/AddOns/FiveSecondRule/FiveSecondRule.lua:199
 gainingMana = true
}
(*temporary) = "attempt to call method 'PrintHelp' (a nil value)"

**Comment by loading-ui** [comment]
**Appreciate the help! This got rid of the SetJustifyV error, however the command /fsr lua error still persists and can't open the addon options as it's giving this error.**

Message: ...face/AddOns/FiveSecondRule/Modules/SlashCommands.lua:35: attempt to call method 'PrintHelp' (a nil value)
Time: Sat Jul 13 21:34:52 2024
Count: 1
Stack: ...face/AddOns/FiveSecondRule/Modules/SlashCommands.lua:35: attempt to call method 'PrintHelp' (a nil value)
[string "@Interface/AddOns/FiveSecondRule/Modules/SlashCommands.lua"]:35: in function `?'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Classic/ChatFrame.lua"]:5016: in function `ChatEdit_ParseText'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Classic/ChatFrame.lua"]:4674: in function `ChatEdit_SendText'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Classic/ChatFrame.lua"]:4710: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:120_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:120_OnEnterPressed"]:1>

Locals: msg = ""
editbox = ChatFrame1EditBox {
 0 = <userdata>
 headerSuffix = ChatFrame1EditBoxHeaderSuffix {
 }
 tabCompleteTableIndex = 1
 chatLanguage = "Common"
 text = "/"
 setText = 0
 customAutoCompleteFunction = <function> defined @Interface/AddOns/Blizzard_ChatFrameBase/Classic/ChatFrame.lua:4199
 autoCompleteParams = <table> {
 }
 chatFrame = ChatFrame1 {
 }
 header = ChatFrame1EditBoxHeader {
 }
 addSpaceToAutoComplete = true
 addHighlightedText = true
 prompt = ChatFrame1EditBoxPrompt {
 }
 languageID = 7
 language = "Common"
}
cmd = ""
(*temporary) = nil
(*temporary) = Frame {
 previousPower = 263
 GetPowerType = <function> defined @Interface/AddOns/FiveSecondRule/FiveSecondRule.lua:157
 0 = <userdata>
 Refresh = <function> defined @Interface/AddOns/FiveSecondRule/FiveSecondRule.lua:180
 Unlock = <function> defined @Interface/AddOns/FiveSecondRule/FiveSecondRule.lua:185
 mp5StartTime = 0
 GetPower = <function> defined @Interface/AddOns/FiveSecondRule/FiveSecondRule.lua:149
 OptionsPanelFrame = FiveSecondRuleOptionsPanelFrame {
 }
 IsWOTLK = <function> defined @Interface/AddOns/FiveSecondRule/FiveSecondRule.lua:60
 Lock = <function> defined @Interface/AddOns/FiveSecondRule/FiveSecondRule.lua:192
 GetPowerMax = <function> defined @Interface/AddOns/FiveSecondRule/FiveSecondRule.lua:153
 UIFactory = <table> {
 }
 Reset = <function> defined @Interface/AddOns/FiveSecondRule/FiveSecondRule.lua:199
 gainingMana = true
}
(*temporary) = "attempt to call method 'PrintHelp' (a nil value)"

**Comment by smp4903** [comment]
Fixed in 902b35c1548e5d930819c03e87abd7bef60790b9.
