### ISSUE TITLE
Error Lua

### ISSUE THREAD

**Issue by Xprit44** [smp4903/FiveSecondRule#32]
Hi,

I have a lua error on version 1.15.3
addon version 1.15.3

here is the message:

Message: ...ace/AddOns/FiveSecondRule/Dependencies/UIFactory.lua:22: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
Time: Fri Jul 19 14:20:20 2024
Count: 1
Stack: ...ace/AddOns/FiveSecondRule/Dependencies/UIFactory.lua:22: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
[string "@Interface/AddOns/FiveSecondRule/Modules/OptionsPanel.lua"]:196: in function `CreateGUI'
[string "@Interface/AddOns/FiveSecondRule/Modules/OptionsPanel.lua"]:20: in function <...rface/AddOns/FiveSecondRule/Modules/OptionsPanel.lua:17>

Locals: self = FiveSecondRuleOptionsPanelFrame {
 UpdateOptionValues = <function> defined @Interface/AddOns/FiveSecondRule/Modules/OptionsPanel.lua:29
 0 = <userdata>
 CreateGUI = <function> defined @Interface/AddOns/FiveSecondRule/Modules/OptionsPanel.lua:64
}
name = "FiveSecondRule"
parent = nil
frame = Frame {
 0 = <userdata>
 content = CADOptionsContent {
 }
 name = "FiveSecondRule"
 title = FiveSecondRuleTitle {
 }
}
ADDON_NAME = "FiveSecondRule"
OptionsPanelFrame = FiveSecondRuleOptionsPanelFrame {
 UpdateOptionValues = <function> defined @Interface/AddOns/FiveSecondRule/Modules/OptionsPanel.lua:29
 0 = <userdata>
 CreateGUI = <function> defined @Interface/AddOns/FiveSecondRule/Modules/OptionsPanel.lua:64
}
colorPickerStateSet = false

**Comment by smp4903** [comment]
Fixed in 902b35c1548e5d930819c03e87abd7bef60790b9.
