### ISSUE TITLE
New bar for mana ticks

### ISSUE THREAD

**Issue by Homeguard** [smp4903/FiveSecondRule#5]
Loving this addon so far with the addition of the mana ticks. The current way of viewing the mana ticks is however not very nice, as the countdown bar appears directly below the players mana bar and is quite small and easily missed.

Could a separate bar be created in the same location as the 5 second timer, so that it appears once the 5 second timer finishes and disappears. So when the 5 second timer disappears a new bar should appear with the countdown of the next mana tick, and maybe it would be best to change the bar flow from left to right (filling up) to differentiate it easily from the 5 second timer.
The new bar should then also disappear once the player reaches 100% mana or the 5 second rule timer is activated again.

I know it might be a lot more work than adding a small countdown line below the mana bar, but it would make it so much better usability wise.

**Comment by smp4903** [comment]
Work in progress - will report back in about 7 hours :-)

**Comment by smp4903** [comment]
Commit 8991db6060973fbae4e4f507e3c0023e9ad2b684:

Redesign the mana ticks to a larger bar that fills up from left to right after the 5SR has been fulfilled. The mana ticks bar is also hidden if the 5SR is broken and the countdown restarts.

For now, the smaller, legacy design has been removed and will later be reintroduced throught custimization in the Addon Settings.

Only few options are available and with little usability as of this moment.
